### ISSUE TITLE
Cache:GetPart() not getting part children

### ISSUE THREAD

**Issue by zshleyp** [Pyseph/ObjectCache#1]
Yeah it just doesnt get the children on the cached part. On the rbxl file, run the script and move TargetPart around. Eventually you'll get the error: Infinite yield possible on 'Pencil:WaitForChild("Handle")'. In the actual place where im using it, Pencil is just the thing keeping it together, while handle (and its children) are the actual visual projectile. Maybe i'm just using your module script wrong.[https://file.io/Wv0lslpkupj0](url) i could provide a video of the issue if you cant replicate it

**Comment by Pyseph** [comment]
Hi — this behavior is intended, as behind the scenes ObjectCache uses BulkMoveTo for movement optimizations. If you would like to move those other parts, you can weld them to the main part which should work.

**Comment by zshleyp** [comment]
The parts are already welded together, and usually it works. But after moving the target part, (which switches the direction the pencils need to travel in) it just doesn't detect the parts  descendants. I'll provide a video in a bit since I have to go to school

**Comment by zshleyp** [comment]
https://github.com/user-attachments/assets/75f63862-6982-42e7-8657-83f0cba4d3c0

**Comment by zshleyp** [comment]
ok this one is using part:Clone and part:Destroy instead of object cache functions

https://github.com/user-attachments/assets/e90865ca-54da-4b87-a8fa-15f887492d26

**Comment by Pyseph** [comment]
This has been addressed as of v1.4.1.

See the DevForum thread for more information: https://devforum.roblox.com/t/objectcache-a-modern-blazing-fast-model-and-part-cache/3104112/42
