### ISSUE TITLE
When Expanding objects the last object created is used twice causing 1 missing object every expansion

### ISSUE THREAD

**Issue by tmbrye** [Pyseph/ObjectCache#3]
Simple script example:
`local ObjectCache = require(game.ServerScriptService.ObjectCache)

local point = Instance.new("Part")
point.Anchored = true
point.Size = Vector3.new(4, 1, 2)
point.TopSurface = Enum.SurfaceType.Smooth
point.BottomSurface = Enum.SurfaceType.Smooth

local myCache = ObjectCache.new(point, 1, workspace)

for i = 1, 3 do
	local newPoint = myCache:GetPart() --point:Clone()
	newPoint.Name = "Part_" .. i
	newPoint.Position = Vector3.new((i+1) * 5, 1, 0)
	newPoint.Parent = workspace
end`

Notice the 2nd part is missing and actually becomes the 3rd part.  If you change the initial cacheSize to be more than 1 it will work correctly.

**Comment by Pyseph** [comment]
Fixed as of https://github.com/Pyseph/ObjectCache/pull/4
